-- 1. 시퀀스 생성 (회원 번호 자동 증가)
CREATE SEQUENCE SEQ_MEMBER_NO START WITH 1 INCREMENT BY 1 NOCACHE;

-- 2. 회원 테이블 생성 (제약조건 포함)
CREATE TABLE "MEMBER" (
    MEMBER_NO      NUMBER         NOT NULL,
    MEMBER_EMAIL   NVARCHAR2(50)  NOT NULL,
    MEMBER_PW      NVARCHAR2(100) NULL,
    MEMBER_TEL     CHAR(11)       NOT NULL,
    ENROLL_DATE    DATE           DEFAULT SYSDATE NOT NULL,
    AUTHOR_LEVEL   NUMBER         DEFAULT 1 NOT NULL,
    AUTH_FL        CHAR(1)        DEFAULT 'N' NOT NULL,
    REAL_NAME      NVARCHAR2(10)  NULL,
    MEMBER_DEL_FL  CHAR(1)        DEFAULT 'N' NOT NULL,
    LOGIN_TYPE     VARCHAR2(10)   NOT NULL,
    OAUTH_PROVIDER VARCHAR2(10)   NULL,
    OAUTH_EMAIL    NVARCHAR2(50)  NULL,
    
    -- 제약조건은 반드시 테이블 생성 괄호 안에 있어야 합니다.
    CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_NO),
    CONSTRAINT UQ_MEMBER_EMAIL UNIQUE (MEMBER_EMAIL),
    CONSTRAINT UQ_MEMBER_TEL   UNIQUE (MEMBER_TEL)
);

COMMENT ON COLUMN "MEMBER".MEMBER_NO      IS '회원 번호(PK)';
COMMENT ON COLUMN "MEMBER".MEMBER_EMAIL   IS '회원 이메일(UQ)';
COMMENT ON COLUMN "MEMBER".MEMBER_PW      IS '회원 비밀번호';
COMMENT ON COLUMN "MEMBER".MEMBER_TEL     IS '회원 연락처(UQ)';
COMMENT ON COLUMN "MEMBER".ENROLL_DATE    IS '회원 가입일';
COMMENT ON COLUMN "MEMBER".AUTHOR_LEVEL   IS '회원 권한 등급';
COMMENT ON COLUMN "MEMBER".AUTH_FL        IS '회원 실명 인증 여부';
COMMENT ON COLUMN "MEMBER".REAL_NAME      IS '회원 실명';
COMMENT ON COLUMN "MEMBER".MEMBER_DEL_FL  IS '회원 탈퇴 여부';
COMMENT ON COLUMN "MEMBER".LOGIN_TYPE     IS '회원 로그인 방식';
COMMENT ON COLUMN "MEMBER".OAUTH_PROVIDER IS '소셜 로그인 제공자';
COMMENT ON COLUMN "MEMBER".OAUTH_EMAIL    IS '소셜 로그인 이메일';